### ISSUE TITLE
Rolens tried to re-open a collection after I deleted the corresponding database

### ISSUE THREAD

**Issue by bartpype** [garraflavatra/rolens#27]
### Bug description

GUI glitch. After I have removed a database, GUI tried to reopen a view with the last used collection from that database. Of course this fails.

### Reproduction

Open a host & collection; do a find query.
Then delete this database.

### Version

0.2

### Environment information

```shell
Intel Mac, MacOS 11.7.4
```

### Severity of this bug

Annoying

**Comment by garraflavatra** [comment]
This should be fixed in ea376f5ba715112529f37e1ec24c6bf86b6489bb.
