### ISSUE TITLE
Copy a collection

### ISSUE THREAD

**Issue by Johbog** [garraflavatra/rolens#63]
### Feature description

I would like to see a feature where I could copy a collection (copy all contents of a collection into a new collection). This was a very useful in a feature in a tool I used previously: Robo 3T.

I think this would be a great addition to Rolens.

### Importance

Nice to have

**Comment by garraflavatra** [comment]
Hi Johan, thanks again! This sounds like a nice feature. I'll try to add this in 0.3.0 as well.

**Comment by garraflavatra** [comment]
I just committed this feature — you could use it already by cloning the `main` branch. Would like to hear your feedback!

It may be a good idea to add an option to copy entire databases too.

**Comment by Johbog** [comment]
Copying an entire database sounds like a great feature.
